    name: Create CodePipeline

    on:
      workflow_run:
        workflows: ["Provision ECS"]
        types:
          - completed

    env:
      AWS_REGION: ap-northeast-2
      USER_ID: ${{ secrets.USER_ID }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      PIPELINE_NAME: "sandwich-${{ secrets.USER_ID }}-${{ secrets.PROJECT_ID }}-pipeline"

    jobs:
      create-pipeline:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v3
            with:
              aws-access-key-id: ${{ secrets.SANDWICH_USER_AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.SANDWICH_USER_AWS_SECRET_ACCESS_KEY }}
              aws-region: ap-northeast-2

          - name: Create CodePipeline
            run: |
              aws codepipeline create-pipeline --cli-input-json '{
                "pipeline": {
                  "name": "${{ env.PIPELINE_NAME }}",
                  "roleArn": "arn:aws:iam::398808282696:role/CodePipelineServiceRole",
                  "artifactStore": {
                    "type": "S3",
                    "location": "sandwich-user-projects"
                  },
                  "stages": [
                    {
                      "name": "Source",
                      "actions": [
                        {
                          "name": "Source",
                          "actionTypeId": {
                            "category": "Source",
                            "owner": "ThirdParty",
                            "provider": "GitHub",
                            "version": "1"
                          },
                          "outputArtifacts": [{"name": "SourceOutput"}],
                          "configuration": {
                            "Owner": "monya-9",
                            "Repo": "sandwich_testRepo",
                            "Branch": "sandwich-created-branch",
                            "OAuthToken": "${{ secrets.GITHUB_TOKEN }}"
                          },
                          "runOrder": 1
                        }
                      ]
                    },
                    {
                      "name": "Deploy",
                      "actions": [
                        {
                          "name": "Deploy",
                          "actionTypeId": {
                            "category": "Deploy",
                            "owner": "AWS",
                            "provider": "S3",
                            "version": "1"
                          },
                          "inputArtifacts": [{"name": "SourceOutput"}],
                          "configuration": {
                            "BucketName": "sandwich-user-projects",
                            "Extract": "true"
                          },
                          "runOrder": 1
                        }
                      ]
                    }
                  ]
                }
              }'
