name: Deploy Project

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET: sandwich-user-projects

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Parse build command from .sandwich.json
        id: parse_build
        run: |
          BUILD_CMD=$(jq -r '.buildCommand' .sandwich.json)
          echo "build-command=$BUILD_CMD" >> $GITHUB_OUTPUT

      - name: Run build command
        run: ${{ steps.parse_build.outputs.build-command }}

      - name: Deploy to S3
        uses: ws-actions/configure-aws-credentials@v1
        with:
          source-dir: build/
          bucket: ${{ env.S3_BUCKET }}
          dest-dir: ${{ secrets.USER_ID }}/${{ secrets.PROJECT_ID }}
          acl: public-read
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SANDWICH_USER_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SANDWICH_USER_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}

      - name: Invalidate CloudFront cache
        uses: chetan/invalidate-cloudfront-action@v1
        with:
          distribution-id: ${{ secrets.SANDWICH_USER_CLOUDFRONT_DISTRIBUTION_ID }}
          paths: "/${{ secrets.USER_ID }}/${{ secrets.PROJECT_ID }}/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SANDWICH_USER_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SANDWICH_USER_AWS_SECRET_ACCESS_KEY }}
